execute pathogen#infect()

filetype on
syntax on
colorscheme Tomorrow-Night-Eighties
set colorcolumn=90
set number
set nocompatible
set hidden
set history=100
set mouse=a

" Search
set hlsearch

" Indentation
filetype indent on
set nowrap
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent

" Remove whitespaces on save
autocmd BufWritePre * :%s/\s\+$//e

let mapleader=","
map <leader>s :source ~/.vimrc<CR>

" NerdTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

nmap <C-n> :NERDTreeToggle<CR>
nmap <leader>j :NERDTreeFind<CR>
let NERDTreeMapActivateNode='<right>'
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.DS_Store', '\~$', '\.swp']

" GitGutter
let g:gitgutter_sign_column_always=1

" Airline
set laststatus=2
" let g:airline_theme = 'base16'
let g:airline_theme = 'base16_tomorrow'
let g:airline_powerline_fonts = 1
